language: node_js
node_js:
  - "8.16.0"
  - "10.16.0"
  - "11.15.0"
cache: npm
install: npm install -g firebase-tools
before_install:
  - npm install
script:
  - npm install -g firebase-tools
  - firebase setup:emulators:firestore --debug
  - npm run test:firestore:emulator &&
  - npm run test:jest
git:
  depth: false
  quiet: true
branches:
  only:
  - master
  - develop
